### ISSUE TITLE
AbemaTV_region_free 这个脚本有办法放在SS服务器上吗

### ISSUE THREAD

**Issue by lanleoean** [larvata/abema-hls-dl#4]
https://openuserjs.org/scripts/Larvata/AbemaTV_region_free
感谢大佬的脚本 PC端很好用
不知道有没有办法放在SS的服务器上 以方便其他设备观看？

**Comment by larvata** [comment]
不能

有实现的方法 但是不划算
如果设备可以自定义host那么可以将那个检测ip的域名解析到自己的服务器上 直接返回200状态就可以绕过

如果不能自定义host 那么只能用中间人攻击的方式替换服务端的响应 由于是SSL的站点 需要自己在ss服务器上准备好证书 并且在观看的设备上信任该证书

安卓设备其实可以用旧版看 12月之前的版本没有ip的严格检测
apkpure.com 这里可以找到旧版

**Comment by lanleoean** [comment]
非常感谢！
